apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260510-135214-nf3a3tdd04u7-service
spec:
  selector:
    app: enterprise-system-20260510-135214-nf3a3tdd04u7
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
